# Generated by Django 6.0.4 on 2026-04-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("client_name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("topological", "Topological Surveying"),
                            ("geotechnical", "Geotechnical Investigation"),
                            ("structural", "Structural Design"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("completion_date", models.DateField()),
                (
                    "image_1",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                (
                    "image_2",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                (
                    "image_3",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                (
                    "image_4",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
            ],
        ),
    ]
