# Generated by Django 6.0.4 on 2026-04-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_project_client_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "service_required",
                    models.CharField(
                        choices=[
                            ("topological", "Topological Surveying"),
                            ("geotechnical", "Geotechnical Investigation"),
                            ("structural", "Structural Design"),
                            ("multiple", "Multiple Services / General"),
                        ],
                        max_length=50,
                    ),
                ),
                ("project_location", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="enquiries/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
